### ISSUE TITLE
Kotlin Native support

### ISSUE THREAD

**Issue by luca992** [afollestad/ulfberht#3]
Is there anything stopping this library from supporting native targets? It would be cool to have true dependency injection support on native. Currently, the only di library for native targets is Kodein and that is service lookup library and not true di.

**Comment by afollestad** [comment]
Unfortunately I don't think this is possible. The annotation processor framework is JVM specific and definitely would not carry over to iOS or native binaries. JavaScript doesn't support generics either, which is pretty important to current core functions.

Reflection or Kodein/KOIN style service location would still have to be used there.
