### ISSUE TITLE
Android ViewModel injection

### ISSUE THREAD

**Issue by afollestad** [afollestad/ulfberht#9]
When view model types are injected, they should be associated with a view model factory for the injector.

**Comment by SAGARSURI** [comment]
I am excited about this feature. Hope it won't be as complicated as Dagger 2's implementation. I don't wanna use Koin but can't waste more time on Dagger 2 also. Looking forward to this amazing library. :)

**Comment by afollestad** [comment]
Available in the latest release 😁

**Comment by SAGARSURI** [comment]
I am really excited to use this library. Thanks for creating this amazing alternative to Dagger. 🗡 
A quick question. Should I be using this in production or wait till 1.0?

**Comment by afollestad** [comment]
It should be stable enough, but there's a strong chance more APIs could change before 1.0 😃
